name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -   
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Docker Latest Image
      uses: shrink/actions-docker-latest-image@v1
      with:
        repository: 'docker.pkg.github.com/github/semantic/semantic'
    - 
      name: Increment Semantic Version
      uses: christian-draeger/increment-semantic-version@1.1.0
      with:
        current-version: ${{ steps.latest.outputs.tag }}
        version-fragment: 'bug'
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: hilvenmatz/naenaebot:${{ steps.bump_version.outputs.next-version }}
